name: Release
on:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: corepack enable
      - run: pnpm i --frozen-lockfile
      - run: pnpm run release

      # Pre-Flight
      - name: Preflight AWS auth
        run: |
          set -e
          aws --version
          aws sts get-caller-identity
          aws s3 ls s3://media-viewer-updates

      # Verify B2 Creds
      - name: Verify B2 S3 creds
        run: |
          aws --version
          aws s3 ls --endpoint-url https://s3.us-east-005.backblazeb2.com
          aws s3 ls s3://media-viewer-updates/ --endpoint-url https://s3.us-east-005.backblazeb2.com

      # Upload to B2 (S3 API)
      - name: Upload artifacts
        run: |
          aws s3 cp release/ s3://media-viewer-updates/ --recursive --acl private
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.B2_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.B2_APP_KEY }}
          AWS_EC2_METADATA_DISABLED: "true"
          AWS_S3_FORCE_PATH_STYLE: "true"