name: Release

on:
  push:
    tags:
      - 'v*'   # run on version tags

permissions:
  contents: write

env:
  # ---- Backblaze S3 (B2) config ----
  AWS_ACCESS_KEY_ID: ${{ secrets.B2_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.B2_APP_KEY }}
  AWS_DEFAULT_REGION: us-east-005
  AWS_REGION: us-east-005
  # Force PATH-STYLE so mixed-case bucket names work
  AWS_S3_USE_PATH_STYLE: "true"
  # Set BOTH endpoint envs so every call picks it up
  AWS_ENDPOINT_URL: https://s3.us-east-005.backblazeb2.com
  AWS_ENDPOINT_URL_S3: https://s3.us-east-005.backblazeb2.com
  # Bucket NAME:
  S3_BUCKET: 4gmXev0u4Um


jobs:

  # -----------------------------
  # macOS build
  # -----------------------------
  build-macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Preflight S3 auth (Backblaze)
        run: |
          set -euo pipefail
          aws --version
          echo "Endpoint: $AWS_ENDPOINT_URL_S3"
          echo "Region:   $AWS_DEFAULT_REGION"
          echo "Bucket:   $S3_BUCKET"
          aws s3api head-bucket --bucket "$S3_BUCKET" \
            --endpoint-url "$AWS_ENDPOINT_URL_S3" \
            --region "$AWS_DEFAULT_REGION"

      - name: Build app (TS + Vite)
        run: pnpm build

      - name: Show artifacts
        run: ls -lah release || true

      - name: Package (macOS universal)
        run: pnpm electron-builder --mac dmg zip --universal --publish never --config.directories.output=release

      - name: Upload to Backblaze (macOS)
        run: |
          echo "Uploading macOS release artifacts..."
          aws s3 cp "release/" "s3://$S3_BUCKET/" \
            --recursive \
            --endpoint-url "$AWS_ENDPOINT_URL_S3" \
            --region "$AWS_DEFAULT_REGION" \
            --acl public-read \
            --exclude "*" \
            --include "latest-mac.yml" \
            --include "*-universal-mac.zip" \
            --include "*-universal-mac.zip.blockmap" \
            --include "*.dmg"

  # -----------------------------
  # Windows build (x64 NSIS)
  # -----------------------------
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --no-frozen-lockfile
        shell: bash

      - name: Preflight S3 auth (Backblaze)
        shell: pwsh
        run: |
          aws --version
          Write-Host "Endpoint: $Env:AWS_ENDPOINT_URL_S3"
          Write-Host "Region:   $Env:AWS_DEFAULT_REGION"
          Write-Host "Bucket:   $Env:S3_BUCKET"
          aws s3api head-bucket --bucket "$Env:S3_BUCKET" `
            --endpoint-url "$Env:AWS_ENDPOINT_URL_S3" `
            --region "$Env:AWS_DEFAULT_REGION"

      - name: Build app (TS + Vite)
        run: pnpm build
        shell: bash

      - name: Show artifacts
        shell: bash
        run: |
          ls -lah release 2>/dev/null || ls -lah dist 2>/dev/null || echo "No release/ or dist/ directory found."

      - name: Package (Windows x64)
        run: pnpm electron-builder --win nsis --x64 --publish never --config.directories.output=release
        shell: bash

      - name: Upload to Backblaze (Windows)
        shell: pwsh
        run: |
          aws s3 cp "release/" "s3://$Env:S3_BUCKET/" `
            --recursive `
            --endpoint-url "$Env:AWS_ENDPOINT_URL_S3" `
            --region "$Env:AWS_DEFAULT_REGION" `
            --acl public-read `
            --exclude "*" `
            --include "latest.yml" `
            --include "*.exe" `
            --include "*.exe.blockmap"